spring:
  application:
    name: test
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher    
      
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none 
  h2:
    console:
      enabled: true
      path: /h2-console
flyway:
  enabled: true 
  locations: classpath:db/migration    
    
server:  
  port: 8080    
    
springdoc:
  swagger-ui:
    config-url: ${SWAGGER_CONFIG_URL:/v3/api-docs/swagger-config}
    url: ${SWAGGER_URL:/v3/api-docs}
    disable-swagger-default-url: true
    operationsSorter: method
    tagsSorter: alpha
    
parameters:
  path: C:\\Users\\maiar\\teste\\exercise.csv    